version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING  # 프로덕션에서는 WARNING 이상만 콘솔에 출력
    formatter: standard
    stream: ext://sys.stdout
  
  # 프로덕션 환경에서는 파일 로깅 추가
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # 루트 로거 설정
  '': 
    level: WARNING
    handlers: [console, file]  # 콘솔과 파일에 모두 로깅
    propagate: false
  
  # 자체 애플리케이션 로거
  app:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  # FastAPI 관련 로거
  fastapi:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  # Uvicorn 관련 로거
  uvicorn:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  uvicorn.error:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  uvicorn.access:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  # 기타 외부 라이브러리 로거
  sqlalchemy:
    level: ERROR
    handlers: [console, file]
    propagate: false
  
  httpx:
    level: ERROR
    handlers: [console, file]
    propagate: false
  
  yaml_config:
    level: WARNING
    handlers: [console, file]
    propagate: true 